language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode10.1
      language: generic
    - os: osx
      osx_image: xcode9.4
      language: generic

install:
  - pip install -r requirements.txt
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install pytest; fi
  - python setup.py build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py build_sphinx; fi
  - python setup.py install

script:
  - pytest
