language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required
    - os: osx
      language: generic
      python: "3.6"

install:
  - pip install -r requirements.txt
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install pytest; fi
  - python setup.py build build_sphinx
  - python setup.py install

script:
  - pytest
